// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA97VNgQbhr3PYw8bUwnZZNxmvGVH6u-Sc',
    appId: '1:1032804601038:web:8b6ace30407e9425b5949f',
    messagingSenderId: '1032804601038',
    projectId: 'clocktantra',
    authDomain: 'clocktantra.firebaseapp.com',
    storageBucket: 'clocktantra.appspot.com',
    measurementId: 'G-HPRRVZ40R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYq1c3TgFxdHQBkWctf41Uy3_jJbROSbg',
    appId: '1:1032804601038:android:2353098b30f94a09b5949f',
    messagingSenderId: '1032804601038',
    projectId: 'clocktantra',
    storageBucket: 'clocktantra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG4stFwR5U8zalcnU7V_8OPkEwsoMKsgk',
    appId: '1:1032804601038:ios:91c66015abcbe565b5949f',
    messagingSenderId: '1032804601038',
    projectId: 'clocktantra',
    storageBucket: 'clocktantra.appspot.com',
    iosBundleId: 'com.example.authenticheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG4stFwR5U8zalcnU7V_8OPkEwsoMKsgk',
    appId: '1:1032804601038:ios:91c66015abcbe565b5949f',
    messagingSenderId: '1032804601038',
    projectId: 'clocktantra',
    storageBucket: 'clocktantra.appspot.com',
    iosBundleId: 'com.example.authenticheck',
  );
}
